// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInTerminal
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "c4bf35e3-bbfd-4575-b525-16f57b348e4f";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidOpenInTerminalCmdSetString = "2fc1b078-e8e7-4b3a-aa8c-60ee82fc3f45";
        public static Guid guidOpenInTerminalCmdSet = new Guid(guidOpenInTerminalCmdSetString);

        public const string guidOpenCurrentInTerminalCmdSetString = "b0d8b470-6293-453f-9c4d-f318226f45fe";
        public static Guid guidOpenCurrentInTerminalCmdSet = new Guid(guidOpenCurrentInTerminalCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenInTerminal = 0x0001;
        public const int OpenCurrentInTerminal = 0x0001;
    }
}