// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInTerminal
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "0a3cf9fa-2fe6-42dc-97df-a0f224cf5854";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidOpenInTerminalCmdSetString = "a807c8ab-0342-4e11-a055-24c7228e2fb0";
        public static Guid guidOpenInTerminalCmdSet = new Guid(guidOpenInTerminalCmdSetString);

        public const string guidOpenCurrentInTerminalCmdSetString = "41dc509b-dae0-40b7-9ad2-0e9809457ddc";
        public static Guid guidOpenCurrentInTerminalCmdSet = new Guid(guidOpenCurrentInTerminalCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenInTerminal = 0x0001;
        public const int OpenCurrentInTerminal = 0x0001;
    }
}